#!/bin/sh

rm -Rf /tmp/dustpan
mkdir /tmp/dustpan
mv /var/www/veejay/public/cache/index.html /tmp/dustpan/
mv /var/www/veejay/public/cache/page /tmp/dustpan/
mv /var/www/veejay/public/cache/rss.html /tmp/dustpan/
curl http://veejay.tv > /dev/null
curl http://veejay.tv/page/1 > /dev/null
curl http://veejay.tv/rss > /dev/null
